window:
  dimensions:
    columns: 100
    lines: 50
  padding:
    x: 10
    y: 10

font:
  normal:
    style: Regular
    family: Roboto Mono
    family: Menlo
    family: Consolas
  bold:
    style: Regular
  size: 16

cursor:
  style: Block

colors:
  primary:
    foreground: '#999DA2'
    background: '#171717'

  normal:
    black: '#171717'
    white: '#999DA2'
      #  green: '#80C159'
      #bright:
      #  green: '#80C159'
