window:
  dimensions:
    columns: 120
    lines: 30
  padding:
    x: 10
    y: 10

font:
  normal:
    style: Regular
    family: Menlo
    family: Consolas
    family: Roboto Mono
  bold:
    style: Regular
  size: 24

cursor:
  style: Block
