window:
  dimensions:
    columns: 120
    lines: 30
  padding:
    x: 0
    y: 0

font:
  normal:
    family: Menlo
  size: 18

colors:
  primary:
    background: '#000000'
    foreground: '#dedede'
  normal:
    black:      '#000000'
    red:        '#c01c28'
    green:      '#26a269'
    yellow:     '#f4b400'
    blue:       '#2a7bde'
    magenta:    '#c061cb'
    cyan:       '#2aa1b3'
    white:      '#dedede'
  bright:
    black:      '#2d333b'
    black:      '#5e5c64'
    red:        '#c01c28'
    green:      '#26a269'
    yellow:     '#f4b400'
    blue:       '#2a7bde'
    magenta:    '#c061cb'
    cyan:       '#2aa1b3'
    white:      '#dedede'

#colors:
#  primary:
#    background: '#22272e'
#    foreground: '#adbac7'
#  normal:
#    black:   '#22272e'
#    red:     '#f47067'
#    green:   '#8ddb8c'
#    yellow:  '#f69d50'
#    blue:    '#6cb6ff'
#    magenta: '#dcbdfb'
#    cyan:    '#96d0ff'
#    white:   '#adbac7'
#  bright:
#    black:   '#768390'
#    red:     '#f47067'
#    green:   '#8ddb8c'
#    yellow:  '#f69d50'
#    blue:    '#6cb6ff'
#    magenta: '#dcbdfb'
#    cyan:    '#96d0ff'
#    white:   '#adbac7'

cursor:
  style: Block
