window:
  dimensions:
    columns: 120
    lines: 60
  padding:
    x: 10
    y: 10

font:
  #offset:
  #y: 8
  normal:
    style: Regular
    family: Consolas
    family: Roboto Mono
    family: Menlo
  bold:
    style: Regular
  size: 14

cursor:
  style: Block

colors:
  # Default colors
  primary:
    background: '0x002b36'
    foreground: '0x839496'

  # Normal colors
  normal:
    black:   '0x073642'
    black:   '0x002b36'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'

  # Bright colors
  bright:
    black:   '0x002b36'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'
