window:
  dimensions:
    columns: 120
    lines: 60
  padding:
    x: 10
    y: 10

font:
  #offset:
  #y: 8
  normal:
    style: Regular
    family: Menlo
    family: Roboto Mono
    family: Consolas
  bold:
    style: Regular
  size: 16

cursor:
  style: Block

colors:
  primary:
    background: '#111415'
    foreground: '#bfc7cc'
    foreground: '#8599b3'
    foreground: '#a3aeb5'
  normal:
    black:      '#111415'
    white:      '#bfc7cc'
    white:      '#a3aeb5'
  bright:
    black:      '#55626a'
