window:
  dimensions:
    columns: 80
    lines: 60
  padding:
    x: 10
    y: 10

font:
  normal:
    style: Regular
    family: Menlo
    family: Roboto Mono
    family: Consolas
  bold:
    style: Regular
  size: 20

cursor:
  style: Block
