window:
  dimensions:
    columns: 120
    lines: 30
  padding:
    x: 0
    y: 0

font:
  normal:
    family: Menlo
  size: 11

colors:
  primary:
    background: '#000000'
    foreground: '#cccccc'
  normal:
    black:   '#000000'
    red:     '#c01c28'
    green:   '#26a269'
    yellow:  '#cc9933'
    blue:    '#12488b'
    magenta: '#a347ba'
    cyan:    '#2aa1b3'
    white:   '#cccccc'
  bright:
    black:   '#22272e'
    red:     '#f66151'
    green:   '#33d17a'
    yellow:  '#cc9933'
    blue:    '#2a7bde'
    magenta: '#c061cb'
    cyan:    '#33c7de'
    white:   '#ffffff'

#colors:
#  primary:
#    background: '#22272e'
#    foreground: '#adbac7'
#  normal:
#    black:   '#22272e'
#    red:     '#f47067'
#    green:   '#8ddb8c'
#    yellow:  '#f69d50'
#    blue:    '#6cb6ff'
#    magenta: '#dcbdfb'
#    cyan:    '#96d0ff'
#    white:   '#adbac7'
#  bright:
#    black:   '#768390'
#    red:     '#f47067'
#    green:   '#8ddb8c'
#    yellow:  '#f69d50'
#    blue:    '#6cb6ff'
#    magenta: '#dcbdfb'
#    cyan:    '#96d0ff'
#    white:   '#adbac7'

cursor:
  style: Block
