window:
  dimensions:
    columns: 90
    lines: 60
  padding:
    x: 10
    y: 10

font:
  normal:
    style: Regular
    family: Roboto Mono
    family: Consolas
    family: Menlo
  bold:
    style: Regular
  size: 16

cursor:
  style: Block
