window:
  dimensions:
    columns: 120
    lines: 60
  padding:
    x: 10
    y: 10

font:
  #offset:
  #y: 8
  normal:
    style: Regular
    family: Consolas
    family: Roboto Mono
    family: Menlo
  bold:
    style: Regular
  size: 13

cursor:
  style: Block

colors:
  primary:
    background: '#2d333b'
    background: '#22272e'
    foreground: '#adbac7'
  normal:
    black:   '#2d333b'
    black:   '#22272e'
    red:     '#f47067'
    green:   '#8ddb8c'
    yellow:  '#f69d50'
    blue:    '#6cb6ff'
    magenta: '#dcbdfb'
    cyan:    '#96d0ff'
    white:   '#adbac7'
  bright:
    black:   '#768390'
    red:     '#f47067'
    green:   '#8ddb8c'
    yellow:  '#f69d50'
    blue:    '#6cb6ff'
    magenta: '#dcbdfb'
    cyan:    '#96d0ff'
    white:   '#adbac7'
