window:
  dimensions:
    columns: 100
    lines: 40

font:
  #offset:
    #y: 10
  normal:
    style: Regular
    family: Roboto Mono
    family: Menlo
    family: Consolas
  bold:
    style: Regular
  size: 22

cursor:
  style: Block

# The 'Dark dimmed' colorscheme from Github.
#colors:
# primary:
#   foreground: '#999DA2'
#   background: '#171717'
#
# normal:
#   black: '#171717'
#   white: '#999DA2'
#     #  green: '#80C159'
#     #bright:
#     #  green: '#80C159'

colors:
  primary:
    background: '#171717'
    background: '#22272e'
    background: '#333a45'
    foreground: '#999da2'
    foreground: '#adbac7'
    foreground: '#768390'
    foreground: '#8d9dac'
  normal:
    black:   '#171717'
    black:   '#22272e'
    black: '#333a45'
    red:     '#f47067'
    green:   '#8ddb8c'
    yellow:  '#f69d50'
    blue:    '#6cb6ff'
    magenta: '#dcbdfb'
    cyan:    '#96d0ff'
    white:   '#768390'
    white:   '#8d9dac'
  bright:
    black:   '#545d68'
    black:   '#768390'
    red:     '#f47067'
    green:   '#8ddb8c'
    yellow:  '#f69d50'
    blue:    '#6cb6ff'
    magenta: '#dcbdfb'
    cyan:    '#96d0ff'
    white:   '#adbac7'
