window:
  dimensions:
    columns: 100
    lines: 20
  padding:
    x: 15
    y: 5

font:
  offset:
    y: 5
  normal:
    family: Roboto Mono
    family: DejaVu Sans Mono
    family: Menlo
    family: Droid Sans Mono
    family: Consolas
  bold:
    style: Regular
  size: 14

cursor:
  style: Underline

colors:
  primary:
    background: '#22272e'
    foreground: '#768390'
  normal:
    black:   '#22272e'
    white:   '#768390'
    red:     '#f47067'
    green:   '#8ddb8c'
    yellow:  '#f69d50'
    blue:    '#6cb6ff'
    magenta: '#dcbdfb'
    cyan:    '#96d0ff'
  bright:
    black:   '#545d78'
    white:   '#768390'
    red:     '#f47067'
    green:   '#8ddb8c'
    yellow:  '#f69d50'
    blue:    '#6cb6ff'
    magenta: '#dcbdfb'
    cyan:    '#96d0ff'
