window:
  dimensions:
    columns: 120
    lines: 30
  padding:
    x: 0
    y: 0

font:
  normal:
    family: Menlo
  size: 18

cursor:
  style: Block

# The 'Dark dimmed' colorscheme from Github.
colors:
  primary:
    background: '#22272e'
    foreground: '#adbac7'
  normal:
    black:  '##22272e'
    red:     '#f47067'
    green:   '#8ddb8c'
    yellow:  '#f69d50'
    blue:    '#6cb6ff'
    magenta: '#dcbdfb'
    cyan:    '#96d0ff'
    white:   '#adbac7'
  bright:
    black:   '#768390'
    red:     '#f47067'
    green:   '#8ddb8c'
    yellow:  '#f69d50'
    blue:    '#6cb6ff'
    magenta: '#dcbdfb'
    cyan:    '#96d0ff'
    white:   '#adbac7'

