

set smartcase
set ignorecase
set smartindent
set cinoptions=(0

set sts=2 ts=8 sw=2 expandtab

au BufRead,BufNewFile *.h set filetype=c
"au BufRead,BufNewFile *.pd set filetype=c

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

set fillchars+=stl:-
set fillchars+=stlnc:-
set hlsearch
set formatoptions+=cro
set wildmode=full

function PrintHighlighter()
	echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<' . synIDattr(synID(line("."),col("."),0),"name") . "> lo<" . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"
endfunction

set background=dark
syntax on

set t_Co=16
set notermguicolors

hi VertSplit          ctermfg=0 ctermbg=7
hi StatusLine         ctermfg=0 ctermbg=7
hi StatusLineNC       ctermfg=0 ctermbg=7
hi Search             ctermfg=0
hi Visual             ctermfg=0 cterm=none
hi NonText            ctermfg=0

hi Comment            ctermfg=8
hi Type               ctermfg=1
hi Include            ctermfg=7
hi Constant           ctermfg=4
hi Special            ctermfg=7
hi Statement          ctermfg=7
hi Normal             ctermfg=7
hi String             ctermfg=6
hi Visual             ctermfg=0
hi Function           ctermfg=5

augroup ft_cpp
    autocmd!
    autocmd Syntax cpp syn match cFunctionName "[a-zA-Z_][a-zA-Z_0-9]*("me=e-1 contained
    autocmd Syntax cpp syn match cFunction "[a-zA-Z_][a-zA-Z_0-9]*(.*{$" contains=cFunctionName,cStorageClass,cType
    autocmd Syntax cpp hi cFunctionName ctermfg=5
augroup end
